version: "3"
services:
  presto:
    image: "starburstdata/presto:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./catalog/postgres-dev.properties:/usr/lib/presto/etc/catalog/postgres-dev.properties
  postgres:
    image: postgres
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
